config/routes.rb
MissionControl::Application.routes.draw do
  resources :check_ins

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render action: 'show', status: :created, location: @check_in }
      else
        format.html { render action: 'new' }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:first_name, :last_name, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/_form.html.erb
<%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing check_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

app/views/check_ins/index.html.erb
<h1>Listing check_ins</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @check_ins.each do |check_in| %>
      <tr>
        <td><%= check_in.first_name %></td>
        <td><%= check_in.last_name %></td>
        <td><%= check_in.time %></td>
        <td><%= link_to 'Show', check_in %></td>
        <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
        <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check in', new_check_in_path %>

app/views/check_ins/new.html.erb
<h1>New check_in</h1>

<%= render 'form' %>

<%= link_to 'Back', check_ins_path %>

app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @check_in.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @check_in.last_name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @check_in.time %>
</p>

<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', check_ins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mission Control</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>